name: omdbassestment
description: Roam software engineer assestment test. A cross platform application that queries from the omdb database for movies as per the users search query.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.0.5 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  intl: ^0.19.0
  page_transition: ^2.0.5
  dio: ^5.4.0
  stacked: ^3.4.1
  toggle_switch: ^2.1.0
  cupertino_icons: ^1.0.2
  connectivity_plus: ^2.2.1
  flutter_spinkit: ^5.1.0
  flutter_dotenv: ^5.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^2.0.0


flutter:


  uses-material-design: true

  assets:
    - assets/
    - .env

  fonts:

    - family: Bold
      fonts:
        - asset: fonts/bold.ttf

    - family: Medium
      fonts:
        - asset: fonts/medium.ttf

    - family: Regular
      fonts:
        - asset: fonts/regular.ttf
